# Nexora Sentinel — One-command local setup
# Usage: .\scripts\setup_local.ps1 -DatabaseUrl "postgresql://..."
#
# Paste your Neon connection string as the argument and this script:
#   1. Writes backend/.env
#   2. Runs both SQL migrations against Neon
#   3. Installs ML dependencies
#   4. Runs data ingestion (last 365 days)
#   5. Trains the model
#   6. Evaluates and logs metrics
#   7. Commits the model artifacts

param(
    [Parameter(Mandatory=$true)]
    [string]$DatabaseUrl
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent

Write-Host "`n=== Nexora Sentinel Setup ===" -ForegroundColor Cyan

# ── 1. Write backend/.env ────────────────────────────────────────────────────
$jwt = "08bbfab93032e9268ac18e4009072398e729fd294e7e98ec7141cac906700a0d"
$envContent = @"
DATABASE_URL=$DatabaseUrl
JWT_SECRET=$jwt
CORS_ORIGINS=http://localhost:5173
MODEL_ARTIFACT_PATH=../ml/artifacts
"@
$envPath = Join-Path $root "backend\.env"
$envContent | Set-Content $envPath -Encoding UTF8
Write-Host "✓ backend/.env written" -ForegroundColor Green

# ── 2. Run migrations ────────────────────────────────────────────────────────
Write-Host "`nRunning database migrations..." -ForegroundColor Yellow
$migration1 = Join-Path $root "backend\migrations\001_initial_schema.sql"
$migration2 = Join-Path $root "backend\migrations\002_seed_admin_user.sql"

try {
    psql $DatabaseUrl -f $migration1
    Write-Host "✓ Migration 001 (schema + regions) applied" -ForegroundColor Green
    psql $DatabaseUrl -f $migration2
    Write-Host "✓ Migration 002 (admin user) applied" -ForegroundColor Green
} catch {
    Write-Host "⚠ psql not found locally. Run migrations via the Neon SQL Editor instead." -ForegroundColor Yellow
    Write-Host "  Paste backend/migrations/001_initial_schema.sql then 002_seed_admin_user.sql" -ForegroundColor Yellow
}

# ── 3. Install ML deps ───────────────────────────────────────────────────────
Write-Host "`nInstalling ML dependencies..." -ForegroundColor Yellow
Push-Location $root
pip install -r ml/requirements.txt --quiet
Write-Host "✓ ML dependencies installed" -ForegroundColor Green

# ── 4. Ingest data ───────────────────────────────────────────────────────────
Write-Host "`nIngesting 365 days of climate + case data (this takes 1-3 min)..." -ForegroundColor Yellow
$env:DATABASE_URL = $DatabaseUrl
python -m ml.ingest.ingest --days-back 365
Write-Host "✓ Data ingested" -ForegroundColor Green

# ── 5. Fetch training data ───────────────────────────────────────────────────
Write-Host "`nFetching training data from Postgres..." -ForegroundColor Yellow
python ml/fetch_training_data.py
Write-Host "✓ Training data fetched" -ForegroundColor Green

# ── 6. Train model ───────────────────────────────────────────────────────────
Write-Host "`nTraining XGBoost model..." -ForegroundColor Yellow
python ml/train.py
Write-Host "✓ Model trained" -ForegroundColor Green

# ── 7. Evaluate ──────────────────────────────────────────────────────────────
Write-Host "`nEvaluating model..." -ForegroundColor Yellow
python ml/evaluate.py
Write-Host "✓ Metrics logged to ml/artifacts/metrics.json" -ForegroundColor Green

# ── 8. Commit artifacts ──────────────────────────────────────────────────────
Write-Host "`nCommitting model artifacts to git..." -ForegroundColor Yellow
git add ml/artifacts/model.json ml/artifacts/explainer.pkl ml/artifacts/metrics.json
git commit -m "feat: trained model artifacts (auto-generated by setup script)"
git push
Write-Host "✓ Artifacts pushed — Render will auto-redeploy" -ForegroundColor Green

Pop-Location

Write-Host "`n=== Setup Complete ===" -ForegroundColor Cyan
Write-Host "Admin login: admin@nexora-sentinel.local / Sentinel2024!" -ForegroundColor White
Write-Host "JWT_SECRET: $jwt" -ForegroundColor White
Write-Host "`nNext: Deploy to Render + Vercel using DEPLOY.md" -ForegroundColor Yellow
